[package]
name = "etch"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
bytes = "1.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = {  version = "1.15.1", features = ["v4"] }
